import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navigator from "./components/Navigator";
import "./globals.css";
import "./layout.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <div className="MainContainer">
            <div className="TitleContainer">
              <h1>Rick y Morty </h1>
              <Navigator/>  
              {children} 
            </div>
        </div>
      </body>
    </html>
  );  
}
